{
 "title": "chiatter",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Full Node Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Blockchain Synced",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chia_stats_sync_status{}" }
   ]
  },
  {
   "title": "Blockchain Height",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chia_stats_current_height{}" }
   ]
  },
  {
   "title": "Amount Farmed",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "XCH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chia_stats_chia_farmed{} / 1000000000000"
    }
   ]
  },
  {
   "title": "Wallet Funds",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "XCH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chia_stats_wallet_funds{} / 1000000000000"
    }
   ]
  },
  {
   "title": "Plot Type Distribution",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chia_stats_og_plots_k32{}", "legendFormat": "K32 (OG)" },
    { "expr": "chia_stats_og_plots_k33{}", "legendFormat": "K33 (OG)" },
    {
     "expr": "chia_stats_portable_plots_k32{}",
     "legendFormat": "K32 (Portable)"
    },
    {
     "expr": "chia_stats_portable_plots_k33{}",
     "legendFormat": "K33 (Portable)"
    },
    {
     "expr": "chia_stats_self_portable_plots_k32{}",
     "legendFormat": "K32 (Portable Self-Pooling)"
    },
    {
     "expr": "chia_stats_self_portable_plots_k33{}",
     "legendFormat": "K33 (Portable Self-Pooling)"
    }
   ]
  },
  {
   "title": "Total Netspace (Estimated)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chia_stats_network_space_size{}"
    }
   ]
  },
  {
   "title": "Time Since Last Win",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Months" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chia_stats_seconds_since_last_win / 2629800"
    }
   ]
  },
  { "title": "Portable Plots - Self Pooling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Plot Count",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chia_stats_self_portable_plots_k32{} + chia_stats_self_portable_plots_k33{}"
    }
   ]
  },
  {
   "title": "Time To Win (Estimated)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Months" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chia_stats_self_portable_time_to_win{} / 2629800"
    }
   ]
  },
  {
   "title": "Total Plots Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chia_stats_self_portable_size{}"
    }
   ]
  },
  { "title": "Portable Plots - Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Plot Count",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chia_stats_portable_plots_k32{} + chia_stats_portable_plots_k33{}"
    }
   ]
  },
  {
   "title": "Time To Win (Estimated)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Months" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chia_stats_portable_time_to_win{} / 2629800"
    }
   ]
  },
  {
   "title": "Total Plots Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chia_stats_portable_size{}" }
   ]
  },
  { "title": "OG Plots", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Plot Count",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chia_stats_og_plots_k32{} + chia_stats_og_plots_k33{}"
    }
   ]
  },
  {
   "title": "Time To Win (Estimated)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Months" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chia_stats_og_time_to_win{} / 2629800"
    }
   ]
  },
  {
   "title": "Total Plots Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chia_stats_og_size{}" }
   ]
  },
  { "title": "TruePool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Pool Members Count",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "truepool_stats_total_farmers{}" }
   ]
  },
  {
   "title": "Time Since Last Win (Pool)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "Hours" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "truepool_stats_seconds_since_last_win / 3600"
    }
   ]
  },
  {
   "title": "Leaderboard Rank",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "prefix:#" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "truepool_stats_farmer_ranking{}"
    }
   ]
  },
  {
   "title": "Current Points",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "truepool_stats_farmer_points{}" }
   ]
  },
  {
   "title": "Time To Win (Estimated)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "Hours" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "truepool_stats_minutes_to_win{} / 60"
    }
   ]
  },
  {
   "title": "Blocks Won",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "truepool_stats_blocks_won{}" }
   ]
  },
  {
   "title": "Invalid Partials (Last 24h)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "truepool_stats_partial_errors_24h{}"
    }
   ]
  },
  {
   "title": "Share Of Upcoming Reward",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "truepool_stats_farmer_points_percentage{}"
    }
   ]
  },
  {
   "title": "Total Rewards Received",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "XCH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "truepool_stats_farmer_pool_earnings{} / 1000000000000"
    }
   ]
  },
  {
   "title": "Total Pool Space (Estimated)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "truepool_stats_total_size{}" }
   ]
  },
  {
   "title": "Pool Share Of Netspace",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "truepool_stats_total_size{} * 100 / chia_stats_network_space_size{}"
    }
   ]
  },
  {
   "title": "Current Difficulty",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "truepool_stats_farmer_difficulty{}"
    }
   ]
  },
  {
   "title": "Contributed Space (Estimated)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "truepool_stats_farmer_estimated_size{}"
    }
   ]
  }
 ]
}