{
 "title": "Chia",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Local Chia Farm", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Blockchain Synced",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chia_stats_sync_status{}" }
   ]
  },
  {
   "title": "Blockchain Height",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chia_stats_current_height{}" }
   ]
  },
  {
   "title": "Wallet Funds",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "XCH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chia_stats_wallet_funds{} / 1000000000000"
    }
   ]
  },
  {
   "title": "Amount Farmed - OG Plots",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "XCH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chia_stats_chia_farmed{} / 1000000000000"
    }
   ]
  },
  {
   "title": "Plot Type Distribution",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chia_stats_plots_k32_og{}", "legendFormat": "K32 (OG)" },
    { "expr": "chia_stats_plots_k33_og{}", "legendFormat": "K33 (OG)" },
    {
     "expr": "chia_stats_plots_k32_portable{}",
     "legendFormat": "K32 (Portable)"
    },
    { "expr": "chia_stats_plots_k33_portable", "legendFormat": "K33 (Portable)" }
   ]
  },
  {
   "title": "Total Network Space (Estimated)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chia_stats_total_size{}" }
   ]
  },
  {
   "title": "Time To Win - OG Plots (Estimated)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Months" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chia_stats_og_time_to_win{} / 2629800"
    }
   ]
  },
  {
   "title": "OG Plot Count",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chia_stats_og_count{}" }
   ]
  },
  {
   "title": "OG Plots Total Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chia_stats_og_size{}" }
   ]
  },
  {
   "title": "Portable Plot Count",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chia_stats_portable_count{}" }
   ]
  },
  {
   "title": "Portable Plots Total Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chia_stats_portable_size{}" }
   ]
  },
  {
   "title": "TruePool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true
  }
 ]
}