global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'prometheus-server'

scrape_configs:
  - job_name: 'chiatter'

    # Override the global default and scrape targets from this job every 10 seconds.
    scrape_interval: 30s

    static_configs:
      - targets: ['localhost:8080']

